baseURL = "https://urgero.org"
languageCode = "en-us"
title = "Mitchell Urgero"
theme = "KeepIt"
publishDir = "docs"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "urgeroorg"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:month/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About Me"
    url = "/about"
    weight = 4

[params]
    since = 2013
    author = "Mitchell Urgero"               # Author's name
    subtitle = "Professional Nerd. Frelance Programmer."       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""
    
    #avatar = "images/portait.jpg" #comment it to use gravatar
    socialShare = true
    
    description = "Personal website for Mitchell Urgero" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    email = "mitchell@urgero.org"   #uncomment and insert your email address to use gravatar


[params.social]
    GitHub = "mitchellurgero"
    Linkedin = "mitchellurgero"
    Twitter = "MitchellUrgero"
    #Instagram = "xxxx"
    Email   = "info@urgero.org"
    Facebook = "mitchell.urgero"
    Telegram = "MitchellU"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    Paypal = "murgero"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
Twitter = true
Facebook = true
#Reddit = true
Linkedin = true
#Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Mitchell Urgero"

  [params.publisher]
    name = "Mitchell Urgero"

    [params.publisher.logo]
      url = "images/portait.jpg"
      width = 127
      height = 40

  [params.logo]
    url = "images/portait.jpg"
    width = 127
    height = 40

  [params.image]
    url = "images/portait.jpg"
    width = 800
    height = 600

[params.gitalk]           
owner = ""              
repo = ""               
clientId = ""           
clientSecret = ""   